.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIFME" "1" "January 2013" "" ""
.
.SH "NAME"
\fBgifme\fR \- animations
.
.SH "SYNOPSIS"
\fBgifme\fR [\fB\-\-delay=N\fR] [\fB\-\-output=FILE\fR] [\fB\-\-[no\-]reverse\fR] FILE [FILE\.\.\.]
.
.SH "DESCRIPTION"
Create animated gifs!
.
.SH "OPTIONS"
.
.TP
\fB\-d\fR, \fB\-\-delay=N\fR
Set the delay between frames (default: 20)
.
.TP
\fB\-\-output=FILE\fR
Path of the generated gif (default: out\.gif)
.
.TP
\fB\-\-[no\-]reverse\fR
Reverse frames to make gif loopable\.
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print a help message describing gifme\'s usage\.
.
.TP
\fB\-\-version\fR
Display the version of gifme\.
.
.SH "EXAMPLE"
Create a gif:
.
.IP "" 4
.
.nf

$ gifme 1\.png 2\.png
Success! Your handsome gif is living at /out\.gif\.
.
.fi
.
.IP "" 0
.
.P
Create a looping gif:
.
.IP "" 4
.
.nf

$ gifme \-\-reverse 1\.png 2\.png
Success! Your handsome gif is living at /out\.gif\.
.
.fi
.
.IP "" 0
.
.P
Pipe in a list of files:
.
.IP "" 4
.
.nf

$ ls *\.png | gifme
Success! Your handsome gif is living at /out\.gif\.
.
.fi
.
.IP "" 0
.
.P
Pipe the path to the gif to another program:
.
.IP "" 4
.
.nf

$ gifme 1\.png 2\.png | cloudapp
Success! Your handsome gif is living at /out\.gif\.
Uploading out\.gif\.\.\. http://cl\.ly/image/1x2f3526230i
.
.fi
.
.IP "" 0

