#!/usr/bin/env ruby

# --delay=N
delay_index = ARGV.index {|arg| arg =~ /--delay=(?<value>.*)/ }
delay       = Regexp.last_match(:value) || '1'
ARGV.slice!(delay_index) if delay_index
unless delay =~ /\A\d+\Z/
  puts 'Delay must be a number.'
  exit
end

# --output=out.gif
output_index = ARGV.index {|arg| arg =~ /--output=(?<value>.*)/ }
output       = (output_index && Regexp.last_match(:value)) || 'out.gif'
ARGV.slice!(output_index) if output_index

# --reverse
reverse = ARGV.delete('--reverse')

if ARGV.empty?
  puts 'No images to gif!'
  exit
end

command = %W(convert -delay #{delay}
                     -loop 0
                     -layers OptimizeTransparency)
command += ARGV
command += ARGV.reverse[1..-2] if reverse
command << output

require 'open3'
stdout, stderr, status = Open3.capture3(*command)
if status.success?
  puts "Success! Your handsome gif is living at #{File.expand_path(output)}."
else
  message = "Something went horribly wrong. :("
  unless stderr.empty?
    message += "\n\nMessage from ImageMagick:\n"
    message += stderr.split("\n").map {|line| '  ' + line }.join("\n")
  end
  puts message
  exit
end
